"""Ensure types advertised in the code-metric system prompt are importable from `galileo`.

If any of these break, the autogenerated scorer prompt will tell the LLM to import a
type that doesn't exist, causing NameError at scorer runtime.
"""

import galileo


def test_scorer_prompt_types_are_exported():
    types = [
        "Trace",
        "LlmSpan",
        "RetrieverSpan",
        "AgentSpan",
        "WorkflowSpan",
        "ToolSpan",
        "Session",
        "Message",
        "Document",
        "SplunkAOMetrics",
    ]
    missing = [name for name in types if not hasattr(galileo, name)]
    assert not missing, f"Types missing from `galileo` public API: {missing}"
