"""Ensure types advertised in the code-metric system prompt are importable from `splunk_ao`.

If any of these break, the autogenerated scorer prompt will tell the LLM to import a
type that doesn't exist, causing NameError at scorer runtime.
"""

import splunk_ao


def test_scorer_prompt_types_are_exported():
    types = [
        "Trace",
        "LlmSpan",
        "RetrieverSpan",
        "AgentSpan",
        "WorkflowSpan",
        "ToolSpan",
        "Session",
        "Message",
        "Document",
        "SplunkAOMetrics",
    ]
    missing = [name for name in types if not hasattr(splunk_ao, name)]
    assert not missing, f"Types missing from `splunk_ao` public API: {missing}"
